In [1]:
!pip install flask


You should consider upgrading via the 'C:\Users\akash\AppData\Local\Programs\Python\Python38\python.exe -m pip install --upgrade pip' command.


In [1]:
from flask import Flask

In [2]:
# # >>> from sklearn.linear_model import LinearRegression
# #----------------------------------------------------------
# reg = LinerRegression()
# ---------- creating the instance for your Linear Regression Class
# reg.fit(X,y)
# ---------- .fit is one of the fuinction provided by linear regression


# This is just for your ref

In [5]:
# Intialize the Flask in the same way
app = Flask(__name__)#dir struct is required and __name__ take care of your dir struct
# created a instance so that we can use any functionality of flask

@app.route("/<name>")# It binds the url with its below function
def hello(name):
    return "<Html><h1>Welcome "+name

app.run(port=5001)# debug= True it does not work in jupyter

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
127.0.0.1 - - [10/Sep/2022 15:03:38] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2022 15:03:47] "GET /varun HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2022 15:03:58] "GET /SRIRAM HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2022 15:04:11] "GET /welcome HTTP/1.1" 200 -


In [6]:
# API 
Application programming Interface
(1)Web Application - 
(2)Machine Learning Model-

Build Interface

In [2]:
import pandas as pd
df = pd.read_csv("hiring.csv")
df.columns = ["experience","test_score","interview_score","salary"]
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [3]:
# I am creating a dummy project project so that we can deploy this
# Salary prediction
# Linear Regression

In [4]:
df.shape

(8, 4)

In [5]:
df.isnull().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [6]:
df.experience.fillna(0,inplace=True)
df.test_score.fillna(df.test_score.mean(),inplace=True)

In [7]:
df.isnull().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

In [8]:
df

experience  test_score  interview_score  salary
0          0    8.000000                9   50000
1          0    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

In [9]:
def conv_dict(x):
    dict={
        "five":5,
        "two":2,
        "seven":7,
        "three":3,
        "ten":10,
        "eleven":11,
        0:0
    }
    return dict[x]

In [10]:
df.experience = df.experience.apply(conv_dict)

In [11]:
df

experience  test_score  interview_score  salary
0           0    8.000000                9   50000
1           0    8.000000                6   45000
2           5    6.000000                7   60000
3           2   10.000000               10   65000
4           7    9.000000                6   70000
5           3    7.000000               10   62000
6          10    7.857143                7   72000
7          11    7.000000                8   80000

In [12]:
X = df.iloc[:,:-1]
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [13]:
y = df.iloc[:,-1]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [14]:
# I am not doing train and test split here, but in real ML model make sure you do it 

In [15]:
from sklearn.linear_model import LinearRegression


In [16]:
lr = LinearRegression()
lr

LinearRegression()

In [17]:
lr.fit(X,y)

LinearRegression()

In [18]:
lr.predict(X)

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [19]:
lr.predict([[3,6,7]])

array([52576.68782509])

In [3]:
lr.predict([[3,6,7]])

NameError: name 'lr' is not defined

# Pickle

In [20]:
import pickle
pickle.dump(lr,open("lr_c37.pkl","wb"))
#

In [4]:
import pickle
lr = pickle.load(open("lr_c37.pkl","rb"))

In [5]:
lr.predict([[3,6,7]])

array([52576.68782509])

In [ ]:
52576.68782509

In [ ]:
52576.687825094275